from enum import StrEnum


class ResultStatus(StrEnum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    UNSUPPORTED = "unsupported"
    NEEDS_APPROVAL = "needs_approval"
    CANCELED = "canceled"


class ProviderState(StrEnum):
    PLANNED = "planned"
    APPROVAL_REQUIRED = "approval_required"
    APPROVED = "approved"
    SUBMITTED = "submitted"
    RUNNING = "running"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    CANCELED = "canceled"


class Stage(StrEnum):
    SCENE_PREFLIGHT = "scene-preflight"
    SCENE_PLAN = "scene-plan"
    PROVIDER_EVIDENCE = "provider-evidence"
    PROVIDER_PLAN = "provider-plan"
    APPROVAL_ISSUE = "approval-issue"
    CONDITION = "condition"
    VIEW_INGEST = "view-ingest"
    PROVIDER_GENERATE = "provider-generate"
    BAKE = "bake"
    EXPORT = "export"


class ApprovalGate(StrEnum):
    FACE_RIGHTS = "face_rights"
    EXTERNAL_EGRESS = "external_egress"
    PAID_COMPUTE = "paid_compute"


class DiagnosticCode(StrEnum):
    INPUT_NOT_FOUND = "INPUT_NOT_FOUND"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    INPUT_UNREADABLE = "INPUT_UNREADABLE"
    EXIF_SENSITIVE_METADATA_PRESENT = "EXIF_SENSITIVE_METADATA_PRESENT"
    BLEND_HEADER_INVALID = "BLEND_HEADER_INVALID"
    BLENDER_NOT_FOUND = "BLENDER_NOT_FOUND"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    OUTPUT_STORAGE_UNAVAILABLE = "OUTPUT_STORAGE_UNAVAILABLE"
    WORKFLOW_NOT_IMPLEMENTED = "WORKFLOW_NOT_IMPLEMENTED"

    # v0.2 execution diagnostics.
    BLENDER_VERSION_MISMATCH = "BLENDER_VERSION_MISMATCH"
    BLENDER_EXECUTION_FAILED = "BLENDER_EXECUTION_FAILED"
    BLENDER_RESPONSE_INVALID = "BLENDER_RESPONSE_INVALID"
    UNTRUSTED_AUTOEXEC_REQUIRED = "UNTRUSTED_AUTOEXEC_REQUIRED"
    SOURCE_CHANGED_DURING_RUN = "SOURCE_CHANGED_DURING_RUN"
    PARENT_MANIFEST_MISMATCH = "PARENT_MANIFEST_MISMATCH"
    PLAN_TAMPERED = "PLAN_TAMPERED"
    SELECTION_AMBIGUOUS = "SELECTION_AMBIGUOUS"
    TARGET_MESH_NOT_FOUND = "TARGET_MESH_NOT_FOUND"
    CAMERA_NOT_FOUND = "CAMERA_NOT_FOUND"
    RIG_NOT_FOUND = "RIG_NOT_FOUND"
    POSE_NONFINITE = "POSE_NONFINITE"
    MISSING_LINKED_ASSET = "MISSING_LINKED_ASSET"
    DEPSGRAPH_TOPOLOGY_CHANGED = "DEPSGRAPH_TOPOLOGY_CHANGED"
    PASS_INVALID = "PASS_INVALID"
    VIEW_ALIGNMENT_MISMATCH = "VIEW_ALIGNMENT_MISMATCH"
    CAMERA_CALIBRATION_MISSING = "CAMERA_CALIBRATION_MISSING"
    SOURCE_POSE_UNKNOWN = "SOURCE_POSE_UNKNOWN"
    UV_MISSING_OR_INVALID = "UV_MISSING_OR_INVALID"
    REPROJECTION_LOW_COVERAGE = "REPROJECTION_LOW_COVERAGE"
    BAKE_CONTEXT_INVALID = "BAKE_CONTEXT_INVALID"
    EXPORT_OPERATOR_UNAVAILABLE = "EXPORT_OPERATOR_UNAVAILABLE"
    GLTF_VALIDATION_FAILED = "GLTF_VALIDATION_FAILED"
    ROUNDTRIP_MISMATCH = "ROUNDTRIP_MISMATCH"
    OUTPUT_COLLISION = "OUTPUT_COLLISION"
    SUBJECT_DECLARATION_REQUIRED = "SUBJECT_DECLARATION_REQUIRED"
    FACE_RIGHTS_CONFIRMATION_REQUIRED = "FACE_RIGHTS_CONFIRMATION_REQUIRED"
    PROVIDER_EVIDENCE_STALE = "PROVIDER_EVIDENCE_STALE"
