from enum import StrEnum


class ResultStatus(StrEnum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    UNSUPPORTED = "unsupported"
    NEEDS_APPROVAL = "needs_approval"


class DiagnosticCode(StrEnum):
    INPUT_NOT_FOUND = "INPUT_NOT_FOUND"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    INPUT_UNREADABLE = "INPUT_UNREADABLE"
    EXIF_SENSITIVE_METADATA_PRESENT = "EXIF_SENSITIVE_METADATA_PRESENT"
    BLEND_HEADER_INVALID = "BLEND_HEADER_INVALID"
    BLENDER_NOT_FOUND = "BLENDER_NOT_FOUND"
    WORKFLOW_NOT_IMPLEMENTED = "WORKFLOW_NOT_IMPLEMENTED"
